### ISSUE TITLE
solmanager disconnects and does not reconnect (even after quitting and then restarting script) cli 'reset system' fixes this

### ISSUE THREAD

**Issue by 5ource** [realms-team/solmanager#66] opened 2016-06-27 23:38 UTC
**python error:**

<pre><code>
> Connecting to /dev/ttyS4... Connection Error: retried 5 times, max allowed is
5
FAIL.
...
</code></pre>

[indefinitely]

**minicom - manager CLI terminal:**
<code><pre>
19028140 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
22628119 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
109480499 : MNGR_ERR_IO SPL_TASK: Disconnect. Error 'Reliable Timeout'
</code></pre>

**Dust manager version:**
<code><pre>

> minfo

Net stack  v1.2.0.0
state:     Oper
mac:       00:17:0d:00:00:60:3e:52
moteid:    1
netid:     1229
blSwVer:   15
ldrSwVer:  0.0.0.0
UTC time:  1027209766:706212
reset st:  100
</code></pre>

**After quitting using 'q', and restarting the script, error persists,  I get:**

<pre><code>
ts4200:~/sol_postInflux_2/solmanager# python solmanager.py             [57/1888]
SolManager - version 0.0.0.5
  - using SmartMesh SDK 1.0.5.138
  - using Sol 0.0.0.5

> Connecting to /dev/ttyS4... Connection Error: retried 5 times, max allowed is
5
FAIL.
Connecting to /dev/ttyS4... 

Mon, 27 Jun 2016 23:34:52 UTC

CRASH in Thread StatsThread!

=== exception type ===
<type 'exceptions.AttributeError'>

=== traceback ===
Traceback (most recent call last):
  File "solmanager.py", line 743, in run
    self.publishNow()
  File "solmanager.py", line 892, in publishNow
    'mac':       self.dustThread.macManager,
AttributeError: 'DustThread' object has no attribute 'macManager'

Connection Error: no HDLC module, did I just disconnect?
FAIL.
Connecting to /dev/ttyS4... Connection Error: retried 5 times, max allowed is 5
FAIL.
....
</code></pre>

**Resetting the manager via CLI command 'reset system' makes it work again.**

**Comment by keomabrun** [comment] 2016-06-29 08:42
@5ource Are you sure about the ports you are using ? Ports might not be consecutive if the dust manager restarts and one of the port is busy (then it will chose the next one). So you will have for instance:
* /dev/ttyS1
* /dev/ttyS2
* /dev/ttyS3
* /dev/ttyS5

Could this make sense ?

**Comment by 5ource** [comment] 2016-06-29 10:24
@keomabrun thanks!
I will double check that.
Btw that error I get is very infrequent and random.

**Comment by keomabrun** [comment] 2016-07-07 07:45
@5ource, can I close this issue ?

**Comment by keomabrun** [comment] 2016-08-31 23:39
This issue occurred again in the Botanical Garden deployment. Maybe a HW issue ?

**Comment by twatteyne** [comment] 2016-09-01 04:24
Keoma, the description above shows a crash dump from Python, and some variable missing. Can you confirm that at least is fixed?

**Comment by twatteyne** [comment] 2016-09-01 04:25
Is the crash dump on the manager side you showed me on Slack related or not? If you think hey are, please copy paste the entire dump here.

**Comment by keomabrun** [comment] 2016-09-01 04:28
@twatteyne, the crash is the same. This crash occurs when the Dust manager is not accessible when running the solmanager.

**Comment by keomabrun** [comment] 2016-09-01 04:30
Here is what the Dust manager shows on serial. Not 100% sure it is linked though.
```
** checkAck ** error cmdId req: 3 ack 9

Fault
R0 = 1
R1 = 40000804
R2 = acf62de6
R3 = acf62de7
R12 = 27
LR = 59803
PC = c92f4
PSR = 61000003
BFAR = 20f20001
CFSR = 8200
HFSR = 40000000
DFSR = 0
AFSR = 0
MFAR = 20f20001
IPSR = 415002
NVIC_ACTIVE0_R = 0
NVIC_ACTIVE1_R = 0
NVIC_SYS_HND_CTRL_R = 70000
SP = 20000898
```

**Comment by 5ource** [comment] 2016-09-03 23:36
I noticed this error almost disappears when I subscribe to only data notifications using the solmanager code. This might be a coincidence though, or less serial communication traffic between linux and dust-manager.

**Comment by keomabrun** [comment] 2016-09-04 01:02
Can you try again ?

**Comment by keomabrun** [comment] 2016-09-05 17:28
@5ource  just tested running the solmanager without the subscription and the solmanager does not crash. We still receive sensor data at the solserver but not the network statistics.

He did so by commenting the two ```self.subscriber.subscribe(``` function calls in https://github.com/realms-team/solmanager/blob/master/solmanager.py#L434.

**Comment by keomabrun** [comment] 2016-09-05 17:30
Following the same lead, I am now testing sending only a sub-part of the subscription:
```NOTIFEVENT```, ```ERROR``` and ```FINISH```.

**Comment by keomabrun** [comment] 2016-09-06 04:43
It is still working after 11 hours. Now enabling NOTIFHEALTHREPORT.

**Comment by keomabrun** [comment] 2016-09-06 13:37
It is still working after 9 hours. Now enabling NOTIFIPDATA.

**Comment by twatteyne** [comment] 2016-09-06 13:41
I believe the issue is that some message doesn't get parsed correctly and causes a crash inthe software. For the manager, all notifications are strictly equivalent. I would place a try/except in the function that is called when the notifications is received.

**Comment by keomabrun** [comment] 2016-09-06 13:49
Incorrect parsing would make the python script to crash. It should not block the tty interface. I should also appear on the logs, which is not the case.
@5ource was suspecting an overflow in the serial communication, @twatteyne  do you think it is possible ?

**Comment by twatteyne** [comment] 2016-09-06 13:52
> Incorrect parsing would make the python script to crash. 
I'm not sure that's true. If the parsing happens in the callback to the SmartMesh SDK, any exception raised will be silently ignored by the SMSDK.

**Comment by keomabrun** [comment] 2016-09-06 14:15
oh okay. Do you mean we should implement the try/except permanently or just for testing then ?

**Comment by twatteyne** [comment] 2016-09-07 07:28
I believe it's a good idea to implement always, as otherwise the error will be silently ignored. It shouldn't cause the manager to crash though.

**Comment by keomabrun** [comment] 2016-09-07 08:03
Agreed.

**Comment by keomabrun** [comment] 2016-09-20 11:55
I've tried:
* ```printf "\033c" > /dev/ttyS4```
* ```echo ^v^o > /dev/ttyS4```
* ```lsof /dev/ttyS4

Nothing works. Only entirely restarting the Dust Manager

**Closed** 2018-02-08 21:33 UTC
